#ifndef THEME_ROSE_H
#define THEME_ROSE_H

// hi

#include "theme.h"

#define COLOR_PINK_ 0xFFC9DF
#define COLOR_PINK_LIGHT_ 0xFFE5F0
#define COLOR_PINK_DARK_ 0xFFA8CB
#define COLOR_WHITE_ 0xFFFFFF
#define COLOR_RED_PINK_ 0xFF0068
#define COLOR_PURPLE_LIGHT_ 0xCAB0FF

#define COLOR_DEFAULT          TRANSPARENT
#define COLOR_BORDER           COLOR_PINK_
#define COLOR_BORDER_FOCUSED   COLOR_PINK_DARK_
#define COLOR_TITLE            COLOR_PURPLE_LIGHT_
#define COLOR_ARTIST           COLOR_PURPLE_LIGHT_
#define COLOR_ALBUM            COLOR_PURPLE_LIGHT_
#define COLOR_STATE_PLAYER     COLOR_PINK_LIGHT_
#define COLOR_STATE_MODES_ON   COLOR_PINK_
#define COLOR_STATE_MODES_OFF  COLOR_PINK_
#define COLOR_TAB              TRANSPARENT
#define COLOR_TAB_ACTIVE       COLOR_PINK_
#define COLOR_PROGRESS         COLOR_PINK_
#define COLOR_TIME             TRANSPARENT
#define COLOR_VOLUME           COLOR_PINK_
#define COLOR_COLUMN_HEADER    COLOR_PINK_LIGHT_
#define COLOR_KEYBIND          TRANSPARENT
#define COLOR_ERROR            COLOR_RED_PINK_
#define COLOR_HIGHLIGHT        COLOR_PINK_LIGHT_
#define COLOR_BACKGROUND       TRANSPARENT
#define COLOR_HIGHLIGHT_BG     COLOR_PURPLE_LIGHT_
#define COLOR_ACTIVE           COLOR_WHITE_

static const Style theme[STYLE_COUNT] = {
  /* slot                     fg                     bg                  attribute */
  [STYLE_DEFAULT]         = { COLOR_DEFAULT,         COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_BORDER]          = { COLOR_BORDER,          COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_BORDER_FOCUSED]  = { COLOR_BORDER_FOCUSED,  COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_TITLE]           = { COLOR_TITLE,           COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_ARTIST]          = { COLOR_ARTIST,          COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_ALBUM]           = { COLOR_ALBUM,           COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_STATE_PLAYER]    = { COLOR_STATE_PLAYER,    COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_STATE_MODES_ON]  = { COLOR_STATE_MODES_ON,  COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_STATE_MODES_OFF] = { COLOR_STATE_MODES_OFF, COLOR_BACKGROUND,   A_DIM     },
  [STYLE_TAB]             = { COLOR_TAB,             COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_TAB_ACTIVE]      = { COLOR_TAB_ACTIVE,      COLOR_BACKGROUND,   A_REVERSE },
  [STYLE_PROGRESS]        = { COLOR_PROGRESS,        COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_TIME]            = { COLOR_TIME,            COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_VOLUME]          = { COLOR_VOLUME,          COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_COLUMN_HEADER]   = { COLOR_COLUMN_HEADER,   COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_KEYBIND]         = { COLOR_KEYBIND,         COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_ERROR]           = { COLOR_ERROR,           COLOR_BACKGROUND,   A_NORMAL  },
  [STYLE_HIGHLIGHT]       = { COLOR_HIGHLIGHT,       COLOR_HIGHLIGHT_BG, A_NORMAL  },
  [STYLE_ACTIVE]          = { COLOR_ACTIVE,          COLOR_HIGHLIGHT_BG, A_NORMAL  },
};

#endif /* THEME_ROSE_H */
